# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Antonio Arellano
title: Data Engineer
email: antonio.arellano.moral@gmail.com
website: https://pezmosca.github.io/CV

# Dark Mode (true/false/never)
darkmode: true

# Social links
#twitter_username: facespics
github_username:  pezmosca
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: antonio-arellano-moral
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/toni_carnet.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Antonio and I'm a Senior Data Engineer.

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Universitat Oberta de Catalunya (Remote) 
        link: uoc.edu
        # link_text: boringcompany.com
        sub_title: Course Instructor
        caption: 2021/02 - Present
        quote: >
          Course: Python for Data Science
        description: | # this will include new lines to allow paragraphs
            **Main responsibilities**: 
            + Introduce, guide, plan, stimulate, focus, motivate and tie together students learning processes with a proactive approach.
            + Address students doubts, offer examples and further explanations, stimulate debates, encourage participation in forums and mark and provide personalized feedback to evaluation tests in order to help students learning processes.
            + Creation of learning resources.
      - layout: left
        title: Mendix/Siemens (Rotterdam)
        link: mendix.com
        # link_text: boringcompany.com
        sub_title: Software Engineer
        caption: 2021/02 - 2021/09
        quote: >
          Main Goal: Python Backend Engineer at the Logging and Monitoring Team.
        description: | # this will include new lines to allow paragraphs
            **Main Tasks**: 
            + Develop and maintain logging, monitoring, and alerting infrastructure for the Mendix Cloud.
            + Ensure all systems are always available by also being responsible for running them in production.
            + On-call duty.
            
            **Projects in which I had big responsibility**:
            + <mark>New servers deployment</mark>: Because of the high demand of the company clients it was needed to deploy new servers that could run Mendix apps, this includes deploy all the necessary in order to be able to log and monitor these apps. I was responsible for configure and deploy all the necessary for having logging, monitoring and alerting of Mendix apps at the new servers.
            + <mark>Enable Datadog logging and tracing</mark>: As a policy from the company all the apps of the team needed to be logging and tracing into datadog, I was responsible for researching how to do it, and enabling a big number of apps with this new feature.
            + <mark>Enable Veracode and Snyk</mark>: As part of the security policy from the company all the apps of the team needed to be analyzed by Veracode and Snyk, I was responsible for researching how to do it, and enabling a big number of apps with this new features.
            
            **Tech Stack used**: AWS (S3, RDS, Route 53, Kinesis, Lambda, SQS), Python (Flask, Django, Celery, SQLAlchemy, Boto3, Requests, Asyncio), ELK stack, InfluxDB, Terraform, Ansible, Docker, Kubernetes, CloudFoundry, Mendix Cloud, Mendix Low-Code.
      - layout: left
        title: Helloprint (Rotterdam)
        link: helloprint.com
        # link_text: boringcompany.com
        sub_title: Data Engineer
        caption: 2019/11 - 2020/11
        quote: >
          Main Goal: Optimize the performance of the company data ecosystem using DataOps methodologies.
        description: | # this will include new lines to allow paragraphs
            **Main Tasks**: 
            + Integrate Data from various resources and manage this data making sure is easily accessible by designing and building data processing platforms.
            + Prepare the data infrastructure to be analyzed by Data Scientists and Data Analyst.
            + Maintain and update the Data pipeline.
            
            **Projects in which I had big responsibility**:
            + <mark>Data Build Tool (DBT) adoption</mark>: I was in charge of the adoption of DBT by the data team, this includes doing research about the new technology, analyze if it can bring value to the business value chain, design and implement a PoC, evangelize the data team about the new technology, migrate non-critical pipelines from the old technology to the new technology, analyze the behavior of the technology with real data, design and implement all the necessary,  including CI/CD and scripts that help automatizing the migration from the old technology to the new technology, in order to be ready to migrate critical pipelines.
            + <mark>Cluster migration</mark>: A cluster of old and outdated machines was used for implementing the data ETL got old and was needed to migrate it to new machines with new specs and an updated OS. I was in charge of the whole process of choosing the new machines specs, installing and configuring in the new cluster all the software existing in the old cluster and leaving a new cluster ready to make the switch to it.
            
            **Tech Stack used**: Airflow, Mara Data Integration, Python, Jenkins, Docker, Kubernetes, Data Build Tool, GitLab CI/CD, Dixa API, Google BigQuery.
      - layout: left
        title: Ludium Lab (Barcelona)
        link: ludiumlab.com
        # link_text: boringcompany.com
        sub_title: Data Engineer (Site Reliability Oriented)
        caption: 2017/05 - 2019/11
        quote: >
          Main Goal: Strategically align the Data department with the Business objectives.
        description: | # this will include new lines to allow paragraphs
            **Main Tasks**: 
            + Being responsible for the creation of the Data department.
            + Design, implement and deploy serverless applications, monitoring systems, and data pipelines for monitoring and data analysis purposes.
            
            **Projects in which I had big responsibility**:
            + <mark>Truman</mark>: Design, implement from scratch and deploy in AWS an ETL platform (called Truman) based on the Kappa architecture that was used to centralize all the data of the company value chain. Some of the use cases were: Billing, Crashlytics, Business Intelligence.
            + <mark>Truman as a Service</mark>: Migrate Truman into AWS services in order to reduce deployment costs.
            + <mark>Caronte</mark>: Implement in Python and deploy in AWS a serverless OAuth2.0 protocol extension that fitted an authorization necessity of the company.
            
            **Tech Stack used**: Python, Java, Kafka, ELK stack, Grafana, JIRA API, AWS (DynamoDB, EC2, Lambda, Kinesis, ELK), Google Cloud.
      - layout: left
        title: Col·legi Oficial de Farmacèutics de Barcelona (Barcelona)
        link: cofb.org
        # link_text: boringcompany.com
        sub_title: Help Desk Intern
        caption: 2016/10 - 2016/09
        quote: >
          Main Goal: Give online support to customers.
        description: | # this will include new lines to allow paragraphs
            **Other responsibilities**: 
            + Maintain a webapp.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Universitat Oberta de Catalunya
        caption: 2020 - Present
        sub_title: Master's degree in Informatics Engineering
        quote: >
          Official degree designed for IT professionals who wish to assume responsibilities in the ICT area of an organization and offer innovative technological solutions to large-scale problems.
        description: | # this will include new lines to allow paragraphs
          This Master enables to:
          + Lead projects and teams in all ICT areas.
          + Carry out all stages of the life cycle of a product or computer system, from its conception to the implantation and maintenance.
          + Select and apply the most appropriate methodology and technology in a particular context.
          + Develop technological solutions in innovative areas such as Artificial Intelligence, Cloud Computing or High Performance Computing.
      - layout: left
        title: Utrecht University
        caption: 2019/08
        sub_title: Project Management - From Theory to Practice
        quote: >
          PRINCE2® Foundation Certificate in Project Management obtained.
        description: | # this will include new lines to allow paragraphs
          Achieved the necessary skills in order to work in a multidisciplinary and multicultural project environment, and to identify the different stages and actors of a project.
      - layout: left
        title: Universitat Politècnica de Catalunya
        caption: 2014 - 2018
        sub_title: Bachelor Degree in Informatics Engineering
        quote: >
          Major in Information Technologies.
        description: | # this will include new lines to allow paragraphs
          <mark>Bachelor Thesis</mark>: Creation of a monitoring and tailing system for errors of ubiquitous devices https://upcommons.upc.edu/handle/2117/122591
          
  #- title: Projects # Title for the section
    #layout: list # Type of content section (list/text)
    #content:
      #- layout: top-middle
        #title: Super awesome project
        #link: github.com/sproogen
        #link_text: Project Website
        #additional_links:
          #- title:  sproogen/modern-resume-theme
            #icon: fab fa-github
            #url: github.com/sproogen/modern-resume-theme
          #- title:  Github page for project (eg. sproogen/modern-resume-theme)
            #icon: fab fa-github
            #url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        #quote: >
          #This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        #description: | # this will include new lines to allow paragraphs
          #I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  #- title: A Little More About Me
    #layout: text
    #content: | # this will include new lines to allow paragraphs
      #Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      #- Rock climbing
      #- Gaming
      #- Knitting
      #- [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      #Look at this cool image  
      #![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
